"""Auto migration

Revision ID: 1840b38f6449
Revises: b5fa82492b15
Create Date: 2026-02-23 15:57:32.317382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1840b38f6449'
down_revision = 'b5fa82492b15'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stops', schema=None) as batch_op:
        batch_op.create_index('idx_stops_geom_gist', ['geom'], unique=False, postgresql_using='gist')

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stops', schema=None) as batch_op:
        batch_op.drop_index('idx_stops_geom_gist', postgresql_using='gist')

    # ### end Alembic commands ###


def upgrade_user_input():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_user_input():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

