"""Auto migration

Revision ID: 1e867a9ef27c
Revises: b5fa82492b15
Create Date: 2026-02-28 18:50:32.999219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e867a9ef27c'
down_revision = 'b5fa82492b15'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route_atlas_stops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_route_atlas_stops_atlas_route_id'), ['atlas_route_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_route_atlas_stops_direction_id'), ['direction_id'], unique=False)

    with op.batch_alter_table('route_osm_stops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_route_osm_stops_direction_id'), ['direction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_route_osm_stops_osm_route_id'), ['osm_route_id'], unique=False)

    with op.batch_alter_table('routes_matched', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_routes_matched_atlas'))
        batch_op.drop_index(batch_op.f('idx_routes_matched_osm'))
        batch_op.create_index(batch_op.f('ix_routes_matched_atlas_route_id'), ['atlas_route_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_routes_matched_osm_route_id'), ['osm_route_id'], unique=False)

    with op.batch_alter_table('stops_matched', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stops_osm_node_id'))
        batch_op.drop_index(batch_op.f('ix_stops_sloid'))
        batch_op.create_index(batch_op.f('ix_stops_matched_osm_node_id'), ['osm_node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stops_matched_sloid'), ['sloid'], unique=False)

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stops_matched', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stops_matched_sloid'))
        batch_op.drop_index(batch_op.f('ix_stops_matched_osm_node_id'))
        batch_op.create_index(batch_op.f('ix_stops_sloid'), ['sloid'], unique=False)
        batch_op.create_index(batch_op.f('ix_stops_osm_node_id'), ['osm_node_id'], unique=False)

    with op.batch_alter_table('routes_matched', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routes_matched_osm_route_id'))
        batch_op.drop_index(batch_op.f('ix_routes_matched_atlas_route_id'))
        batch_op.create_index(batch_op.f('idx_routes_matched_osm'), ['osm_route_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_routes_matched_atlas'), ['atlas_route_id'], unique=False)

    with op.batch_alter_table('route_osm_stops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_route_osm_stops_osm_route_id'))
        batch_op.drop_index(batch_op.f('ix_route_osm_stops_direction_id'))

    with op.batch_alter_table('route_atlas_stops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_route_atlas_stops_direction_id'))
        batch_op.drop_index(batch_op.f('ix_route_atlas_stops_atlas_route_id'))

    # ### end Alembic commands ###


def upgrade_user_input():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_user_input():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

