"""add is_non_gtfs to line_families

Revision ID: 20ae98d97a07
Revises: 20260514_000002
Create Date: 2026-05-15 16:24:19.816870

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20ae98d97a07'
down_revision = '20260514_000002'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_families', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_non_gtfs', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_families', schema=None) as batch_op:
        batch_op.drop_column('is_non_gtfs')
    # ### end Alembic commands ###

