"""Auto migration

Revision ID: 34cb04acd397
Revises: 0fd9b8d7a1c4
Create Date: 2026-04-05 16:53:39.473870

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '34cb04acd397'
down_revision = '0fd9b8d7a1c4'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP INDEX IF EXISTS ix_osm_pairs_node_id_1')
    op.execute('DROP INDEX IF EXISTS ix_osm_pairs_node_id_2')
    op.execute('DROP TABLE IF EXISTS osm_pairs')

    op.execute('DROP INDEX IF EXISTS ix_osm_trios_middle_node_id')
    op.execute('DROP INDEX IF EXISTS ix_osm_trios_side_node_id_1')
    op.execute('DROP INDEX IF EXISTS ix_osm_trios_side_node_id_2')
    op.execute('DROP TABLE IF EXISTS osm_trios')

    op.execute('ALTER TABLE osm_nodes DROP COLUMN IF EXISTS way_node_ids')
    op.execute('ALTER TABLE osm_nodes DROP COLUMN IF EXISTS source_way_id')
    op.execute('ALTER TABLE osm_nodes DROP COLUMN IF EXISTS is_way')

    op.execute('ALTER TABLE routes_matched DROP COLUMN IF EXISTS atlas_route_short_name')
    op.execute('ALTER TABLE routes_matched DROP COLUMN IF EXISTS atlas_route_long_name')
    op.execute('ALTER TABLE routes_matched DROP COLUMN IF EXISTS osm_route_name')

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routes_matched', schema=None) as batch_op:
        batch_op.add_column(sa.Column('osm_route_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('atlas_route_long_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('atlas_route_short_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    with op.batch_alter_table('osm_nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_way', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('source_way_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('way_node_ids', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))

    op.create_table('osm_trios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('middle_node_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('side_node_id_1', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('side_node_id_2', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['middle_node_id'], ['osm_nodes.osm_node_id'], name=op.f('osm_trios_middle_node_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['side_node_id_1'], ['osm_nodes.osm_node_id'], name=op.f('osm_trios_side_node_id_1_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['side_node_id_2'], ['osm_nodes.osm_node_id'], name=op.f('osm_trios_side_node_id_2_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('osm_trios_pkey'))
    )
    with op.batch_alter_table('osm_trios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_osm_trios_side_node_id_2'), ['side_node_id_2'], unique=False)
        batch_op.create_index(batch_op.f('ix_osm_trios_side_node_id_1'), ['side_node_id_1'], unique=False)
        batch_op.create_index(batch_op.f('ix_osm_trios_middle_node_id'), ['middle_node_id'], unique=False)

    op.create_table('osm_pairs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('node_id_1', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('node_id_2', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('group_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['node_id_1'], ['osm_nodes.osm_node_id'], name=op.f('osm_pairs_node_id_1_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id_2'], ['osm_nodes.osm_node_id'], name=op.f('osm_pairs_node_id_2_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('osm_pairs_pkey'))
    )
    with op.batch_alter_table('osm_pairs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_osm_pairs_node_id_2'), ['node_id_2'], unique=False)
        batch_op.create_index(batch_op.f('ix_osm_pairs_node_id_1'), ['node_id_1'], unique=False)

    # ### end Alembic commands ###

