"""Auto migration

Revision ID: 46c936099717
Revises: 2a1c9f7c2b3a
Create Date: 2025-08-14 18:07:37.841663

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '46c936099717'
down_revision = '2a1c9f7c2b3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atlas_stops', schema=None) as batch_op:
        batch_op.drop_column('routes_atlas')
        batch_op.drop_column('routes_hrdf')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atlas_stops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('routes_hrdf', mysql.JSON(), nullable=True))
        batch_op.add_column(sa.Column('routes_atlas', mysql.JSON(), nullable=True))

    # ### end Alembic commands ###
