"""Auto migration

Revision ID: 647fb683a8d3
Revises: b5fa82492b15
Create Date: 2026-03-13 19:07:58.364619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '647fb683a8d3'
down_revision = 'b5fa82492b15'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('osm_pairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id_1', sa.String(length=100), nullable=False),
    sa.Column('node_id_2', sa.String(length=100), nullable=False),
    sa.Column('group_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['node_id_1'], ['osm_nodes.osm_node_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id_2'], ['osm_nodes.osm_node_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('osm_pairs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_osm_pairs_node_id_1'), ['node_id_1'], unique=False)
        batch_op.create_index(batch_op.f('ix_osm_pairs_node_id_2'), ['node_id_2'], unique=False)

    op.create_table('osm_trios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('middle_node_id', sa.String(length=100), nullable=False),
    sa.Column('side_node_id_1', sa.String(length=100), nullable=False),
    sa.Column('side_node_id_2', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['middle_node_id'], ['osm_nodes.osm_node_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['side_node_id_1'], ['osm_nodes.osm_node_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['side_node_id_2'], ['osm_nodes.osm_node_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('osm_trios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_osm_trios_middle_node_id'), ['middle_node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_osm_trios_side_node_id_1'), ['side_node_id_1'], unique=False)
        batch_op.create_index(batch_op.f('ix_osm_trios_side_node_id_2'), ['side_node_id_2'], unique=False)

    with op.batch_alter_table('osm_stop_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_osm_stop_groups_node_id_1'))
        batch_op.drop_index(batch_op.f('ix_osm_stop_groups_node_id_2'))

    op.drop_table('osm_stop_groups')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('osm_stop_groups',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('node_id_1', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('node_id_2', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('group_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['node_id_1'], ['osm_nodes.osm_node_id'], name=op.f('osm_stop_groups_node_id_1_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id_2'], ['osm_nodes.osm_node_id'], name=op.f('osm_stop_groups_node_id_2_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('osm_stop_groups_pkey'))
    )
    with op.batch_alter_table('osm_stop_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_osm_stop_groups_node_id_2'), ['node_id_2'], unique=False)
        batch_op.create_index(batch_op.f('ix_osm_stop_groups_node_id_1'), ['node_id_1'], unique=False)

    with op.batch_alter_table('osm_trios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_osm_trios_side_node_id_2'))
        batch_op.drop_index(batch_op.f('ix_osm_trios_side_node_id_1'))
        batch_op.drop_index(batch_op.f('ix_osm_trios_middle_node_id'))

    op.drop_table('osm_trios')
    with op.batch_alter_table('osm_pairs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_osm_pairs_node_id_2'))
        batch_op.drop_index(batch_op.f('ix_osm_pairs_node_id_1'))

    op.drop_table('osm_pairs')
    # ### end Alembic commands ###

