"""Add matching_notes to stops_matched

Revision ID: 92db95fe03f7
Revises: 1e867a9ef27c
Create Date: 2026-03-02 14:32:15.100327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92db95fe03f7'
down_revision = '1e867a9ef27c'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stops_matched', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matching_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stops_matched', schema=None) as batch_op:
        batch_op.drop_column('matching_notes')

    # ### end Alembic commands ###

