"""Auto migration

Revision ID: e04c24ed3e50
Revises: 34cb04acd397
Create Date: 2026-04-08 22:17:05.865390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e04c24ed3e50'
down_revision = '34cb04acd397'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_stats_buckets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('atlas_operator', sa.String(length=100), nullable=True),
    sa.Column('atlas_duplicate', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('osm_group_kind', sa.String(length=50), nullable=True),
    sa.Column('effective_stop_type', sa.String(length=50), nullable=True),
    sa.Column('match_type', sa.String(length=50), nullable=True),
    sa.Column('is_ferry_terminal', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_tram_stop', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_station', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_platform', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_stop_position', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_aerialway_station', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('total_atlas', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('matched_atlas', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('unmatched_atlas', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('matched_pairs', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_osm_stops', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('matched_osm_stops', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_osm_nodes', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('global_stats_buckets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_global_stats_buckets_atlas_operator'), ['atlas_operator'], unique=False)
        batch_op.create_index('idx_gsb_scope_effective', ['scope', 'effective_stop_type'], unique=False)
        batch_op.create_index('idx_gsb_match_type', ['match_type'], unique=False)
        batch_op.create_index('idx_gsb_group_kind', ['osm_group_kind'], unique=False)
        batch_op.create_index('idx_gsb_atlas_duplicate', ['atlas_duplicate'], unique=False)

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_stats_buckets', schema=None) as batch_op:
        batch_op.drop_index('idx_gsb_atlas_duplicate')
        batch_op.drop_index('idx_gsb_group_kind')
        batch_op.drop_index('idx_gsb_match_type')
        batch_op.drop_index('idx_gsb_scope_effective')
        batch_op.drop_index(batch_op.f('ix_global_stats_buckets_atlas_operator'))

    op.drop_table('global_stats_buckets')
    # ### end Alembic commands ###

